services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - ./wordpress:/var/www/html
  
  db:
    image: mariadb:10.11
    restart: always
    ports:
        - 3306:3306
    volumes:
        - .docker/db/data:/var/lib/mysql
        - .docker/logs:/var/log/mysql
        - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
        - .docker/db/sql:/docker-entrypoint-initdb.d
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_RANDOM_ROOT_PASSWORD: '1'

  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
      - .docker/redis/data:/data
    ports:
      - 6379:6379